name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: Build with bundler
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Test with Rake
      run: bundle exec rake coverage

    - name: Send code coverage
      run: |
        echo "Git branch: $GIT_BRANCH"
        codeclimate-test-reporter
      env:
        GIT_BRANCH: ${{GITHUB_REF/refs\/heads\//}}
        CODECLIMATE_REPO_TOKEN: ${{secrets.CC_TEST_REPORTER_ID}}
